\documentclass[acmsmall]{acmart}

% workaround for duplicate symbols:
\let\oldBbbk\Bbbk%
\let\Bbbk\undefined%

% tight lists:
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}

% lhs2TeX:
%include polycode.fmt
%format aaa

%%
%% \BibTeX command to typeset BibTeX logo in the docs
\AtBeginDocument{%
  \providecommand\BibTeX{{%
    Bib\TeX}}}

%% Rights management information.  This information is sent to you
%% when you complete the rights form.  These commands have SAMPLE
%% values in them; it is your responsibility as an author to replace
%% the commands and values with those provided to you when you
%% complete the rights form.
\setcopyright{acmlicensed}
\copyrightyear{2018}
\acmYear{2018}
\acmDOI{XXXXXXX.XXXXXXX}

%%
%% These commands are for a JOURNAL article.
\acmJournal{JACM}
\acmVolume{37}
\acmNumber{4}
\acmArticle{111}
\acmMonth{8}

%%
%% Submission ID.
%% Use this when submitting an article to a sponsored event. You'll
%% receive a unique submission ID from the organizers
%% of the event, and this ID should be used as the parameter to this command.
%%\acmSubmissionID{123-A56-BU3}

%%
%% For managing citations, it is recommended to use bibliography
%% files in BibTeX format.
%%
%% You can then either use BibTeX with the ACM-Reference-Format style,
%% or BibLaTeX with the acmnumeric or acmauthoryear sytles, that include
%% support for advanced citation of software artefact from the
%% biblatex-software package, also separately available on CTAN.
%%
%% Look at the sample-*-biblatex.tex files for templates showcasing
%% the biblatex styles.
%%

%%
%% The majority of ACM publications use numbered citations and
%% references.  The command \citestyle{authoryear} switches to the
%% "author year" style.
%%
%% If you are preparing content for an event
%% sponsored by ACM SIGGRAPH, you must use the "author year" style of
%% citations and references.
%% Uncommenting
%% the next command will enable that style.
\citestyle{acmauthoryear}

% Preamble:
%format TmInf       = "\Varid{Tm}_{\uparrow}"
%format TmChk       = "\Varid{Tm}_{\downarrow}"
%format |>          = "\triangleright"
%format :>          = "\mathbin{{:}\triangleright}"
%format :->         = "\mathbin{{:}\mkern-5mu\rightarrow}"
%format :@:         = "\mathbin{{:}@{:}}"
%format γ           = "\gamma"
%format τ           = "\tau"
%format τ'          = "\tau^{\prime}"
% Support Unicode characters.
%% \usepackage[T1]{fontenc} %% for diacritics: the default is 'OT1'
\usepackage[utf8]{inputenc} %% pdflatex: For UTF-8 input support.
\usepackage{newunicodechar} %% Map Unicode characters to LaTeX commands.

% Packages with various characters.
\usepackage{textgreek}

% Unicode character mapping.
\newunicodechar{λ}{{\textlambda}}
\newunicodechar{τ}{{\texttau}}

% Packages for type systems.
\usepackage{mathpartir}

%%
%% end of the preamble, start of the body of the document source.
\begin{document}

%%
%% The "title" command has an optional parameter,
%% allowing the author to define a "short title" to be used in page headers.
% Document title
\title{Thinning Thinnings: Safe and Efficient Binders}

%%
%% The "author" command and its associated commands are used to define
%% the authors and their affiliations.
%% Of note is the shared affiliation of the first two authors, and the
%% "authornote" and "authornotemark" commands
%% used to denote shared contribution to the research.
\author{April Gonçalves}
\email{april@@cyberglot.me}
\affiliation{%
    \institution{University of Strathclyde}
      \city{Glasgow}
        \country{UK}
  }
\author{Wen Kokke}
\email{me@@wen.works}
\affiliation{%
    \institution{Well-Typed}
      \city{Glasgow}
        \country{UK}
  }

%%
%% By default, the full list of authors will be used in the page
%% headers. Often, this list is too long, and will overlap
%% other information printed in the page headers. This command allows
%% the author to define a more concise list
%% of authors' names for this purpose.

%%
%% The abstract is a short summary of the work to be presented in the
%% article.
\begin{abstract}
  To be written last\ldots{}
\end{abstract}

%%
%% The code below is generated by the tool at http://dl.acm.org/ccs.cfm.
%% Please copy and paste the code instead of the example below.
%%
\begin{CCSXML}
<ccs2012>
 <concept>
  <concept_id>00000000.0000000.0000000</concept_id>
  <concept_desc>Do Not Use This Code, Generate the Correct Terms for Your Paper</concept_desc>
  <concept_significance>500</concept_significance>
 </concept>
 <concept>
  <concept_id>00000000.00000000.00000000</concept_id>
  <concept_desc>Do Not Use This Code, Generate the Correct Terms for Your Paper</concept_desc>
  <concept_significance>300</concept_significance>
 </concept>
 <concept>
  <concept_id>00000000.00000000.00000000</concept_id>
  <concept_desc>Do Not Use This Code, Generate the Correct Terms for Your Paper</concept_desc>
  <concept_significance>100</concept_significance>
 </concept>
 <concept>
  <concept_id>00000000.00000000.00000000</concept_id>
  <concept_desc>Do Not Use This Code, Generate the Correct Terms for Your Paper</concept_desc>
  <concept_significance>100</concept_significance>
 </concept>
</ccs2012>
\end{CCSXML}

\ccsdesc[500]{Do Not Use This Code~Generate the Correct Terms for Your Paper}
\ccsdesc[300]{Do Not Use This Code~Generate the Correct Terms for Your Paper}
\ccsdesc{Do Not Use This Code~Generate the Correct Terms for Your Paper}
\ccsdesc[100]{Do Not Use This Code~Generate the Correct Terms for Your Paper}

%%
%% Keywords. The author(s) should pick words that accurately describe
%% the work being presented. Separate the keywords with commas.
% Mandatory.
\keywords{\textcolor{red}{TODO: Set keywords}}

\received{20 February 2007}
\received[revised]{12 March 2009}
\received[accepted]{5 June 2009}

%%
%% This command processes the author and affiliation and title
%% information and builds the first part of the formatted document.
\maketitle

\section{Introduction}\label{introduction}

\begin{itemize}
\tightlist
\item[$\square$]
  Define the STλC using \emph{safe} combinators.
\item[$\square$]
  Explain the efficient issues with safe combinators.
\end{itemize}

\begin{code}
type data Nat = Z | S Nat
\end{code}

\begin{code}
data Ix (n :: Nat) where
  FZ  ::          Ix (S n)
  FS  :: Ix n ->  Ix (S n)
\end{code}

\begin{code}
data Ty
  =  Bot
  |  Ty :-> Ty
\end{code}

\begin{code}
data TmInf  n
  =  Ann  (TmChk n) Ty
  |  Var  (Ix n)
  |  App  (TmInf n) (TmChk n)
\end{code}

\begin{code}
data TmChk  n
  =  Inf  (TmInf n)
  |  Lam  (TmChk (S n))
\end{code}

\begin{code}
data Env (n :: Nat) (a :: Type) where
  Nil   ::                  Env  Z      a
  (:>)  :: Env n a -> a ->  Env  (S n)  a
\end{code}

\begin{code}
(!!) :: Env n a -> Ix n -> a
γ :> a  !! FZ    = a
γ :> a  !! FS i  = γ !! i
\end{code}

\begin{code}
check :: Env n Ty -> TmChk n -> Ty -> Bool
check γ  (Inf  e)     τ           = infer γ e == Just τ
check γ  (Lam  e)     (τ :-> τ')  = check (γ :> τ) e τ'
\end{code}

\begin{code}
infer :: Env n Ty -> TmInf n -> Maybe Ty
infer γ = \case
  Ann e τ   | check γ e τ                                 -> Just τ
  Var i                                                   -> Just (γ !! i)
  App e e'  | Just (τ :-> τ') <- infer γ e, check γ e' τ  -> Just τ'
  _                                                       -> Nothing
\end{code}

\begin{code}
idTm :: TmInf n
idTm = Ann (Lam (Inf (Var FZ))) (Bot :-> Bot)
\end{code}

\begin{itemize}
\tightlist
\item[$\square$]
  Add an example that requires thinnings and composition
\end{itemize}

\section{The Fast And The Faithful}\label{the-fast-and-the-faithful}

\begin{itemize}
\tightlist
\item[$\square$]
  Explain the technique to control the type representation through lies.
\item[$\square$]
  Define the \emph{fast and faithful} combinators.
\item[$\square$]
  Give special attention to thinning composition using \texttt{PDEP}.
\item[$\square$]
  Explain the QuickCheck test suite.
\item[$\square$]
  Explain why we're not proving equivalence.
\end{itemize}

\begin{code}
data (m :: Nat) >= (n :: Nat) where
  KeepAll  ::                 m  >=    m
  KeepOne  ::  m >= n  ->  S  m  >= S  n
  DropOne  ::  m >= n  ->  S  m  >=    n
\end{code}

\begin{code}
data Th f m = Th (m >= n) (f n)
\end{code}

\begin{code}
data TmInf (n :: Nat) where
  Ann  :: TmChk n     -> Ty          ->  TmInf n
  Var  ::                                TmInf Z
  App  :: Th TmInf n  -> Th TmChk n  ->  TmInf n
\end{code}

\begin{code}
data TmChk  (n :: Nat) where
  Inf  :: TmInf n      ->  TmChk n
  Lam  :: TmChk (S n)  ->  TmChk n
\end{code}

\section{Experimental Evaluation}\label{experimental-evaluation}

\begin{itemize}
\tightlist
\item[$\square$]
  Explain the experimental evaluation.
\end{itemize}

%%
%% The acknowledgments section is defined using the "acks" environment
%% (and NOT an unnumbered section). This ensures the proper
%% identification of the section in the article metadata, and the
%% consistent spelling of the heading.
% Optional. Acknowledgements.

%%
%% The next two lines define the bibliography style to be used, and
%% the bibliography file.
\bibliographystyle{ACM-Reference-Format}
\bibliography{bibliography.bib}

% TODO: Support appendices.

\end{document}
\endinput
%%
%% End of file `sample-acmsmall.tex'.
